[package]
name = "rust_ray"
version = "0.1.0"
edition = "2021"
authors = ["ararem <48875125+Ararem@users.noreply.github.com>"]
# description = ""
readme = "README.md"
license = "MIT OR Apache-2.0"  # https://spdx.org/licenses/
build = "build.rs" #file to run on build



# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Helper/Dev-tool dependencies
shadow-rs = "0.17.1"
color-eyre = "0.6.2"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["json", "env-filter", "fmt", "std"] }
pretty_assertions = "1.3.0"
tracing-error = "0.2.0"
color-backtrace = "0.5.1"
indoc = "1.0.7"
clap = { version = "4", features=["unicode", "wrap_help", "string", "error-context", "unicode", "color", "usage", "derive"] }
clap_autocomplete = "0.4.0"

[build-dependencies]
shadow-rs = "0.17.1" #Needs to run at build-time, so include as build dependency