[package]
name = "rust_ray"
version = "0.1.0"
edition = "2021"
authors = ["ararem <48875125+Ararem@users.noreply.github.com>"]
# description = ""
readme = "README.md"
license = "MIT OR Apache-2.0"  # https://spdx.org/licenses/
build="build.rs" #file to run on build


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shadow-rs = "0.17.1"

[build-dependencies]
shadow-rs = "0.17.1"